myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: "50"  

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['joint_L1', 'joint_L2']
    right_wheel: ['joint_R1','joint_R2']
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]


